/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables;


import histopatologialab.core.db.Public;
import histopatologialab.core.db.tables.records.LabReportecitasporfechaRecord;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabReportecitasporfecha extends TableImpl<LabReportecitasporfechaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lab_reportecitasporfecha</code>
     */
    public static final LabReportecitasporfecha LAB_REPORTECITASPORFECHA = new LabReportecitasporfecha();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LabReportecitasporfechaRecord> getRecordType() {
        return LabReportecitasporfechaRecord.class;
    }

    /**
     * The column <code>public.lab_reportecitasporfecha.cod_examen</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, Integer> COD_EXAMEN = createField(DSL.name("cod_examen"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.fec_examen</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> FEC_EXAMEN = createField(DSL.name("fec_examen"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.num_examen</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> NUM_EXAMEN = createField(DSL.name("num_examen"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.fecha_examen</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, LocalDate> FECHA_EXAMEN = createField(DSL.name("fecha_examen"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.nombre_paciente</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> NOMBRE_PACIENTE = createField(DSL.name("nombre_paciente"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.tipo_identificacion</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> TIPO_IDENTIFICACION = createField(DSL.name("tipo_identificacion"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.identificacion</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> IDENTIFICACION = createField(DSL.name("identificacion"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.ocupacion</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> OCUPACION = createField(DSL.name("ocupacion"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.numero_ficha</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> NUMERO_FICHA = createField(DSL.name("numero_ficha"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.diagnosticos_diferenciales</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> DIAGNOSTICOS_DIFERENCIALES = createField(DSL.name("diagnosticos_diferenciales"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.req_biopsia</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> REQ_BIOPSIA = createField(DSL.name("req_biopsia"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.req_frote</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> REQ_FROTE = createField(DSL.name("req_frote"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lab_reportecitasporfecha.estado_examen</code>.
     */
    public final TableField<LabReportecitasporfechaRecord, String> ESTADO_EXAMEN = createField(DSL.name("estado_examen"), SQLDataType.VARCHAR, this, "");

    private LabReportecitasporfecha(Name alias, Table<LabReportecitasporfechaRecord> aliased) {
        this(alias, aliased, new Field[0]);
    }

    private LabReportecitasporfecha(Name alias, Table<LabReportecitasporfechaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    /**
     * Create an aliased <code>public.lab_reportecitasporfecha</code> table reference
     */
    public LabReportecitasporfecha(String alias) {
        this(DSL.name(alias), LAB_REPORTECITASPORFECHA);
    }

    /**
     * Create an aliased <code>public.lab_reportecitasporfecha</code> table reference
     */
    public LabReportecitasporfecha(Name alias) {
        this(alias, LAB_REPORTECITASPORFECHA);
    }

    /**
     * Create a <code>public.lab_reportecitasporfecha</code> table reference
     */
    public LabReportecitasporfecha() {
        this(DSL.name("lab_reportecitasporfecha"), null);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public LabReportecitasporfecha as(String alias) {
        return new LabReportecitasporfecha(DSL.name(alias), this, parameters);
    }

    @Override
    public LabReportecitasporfecha as(Name alias) {
        return new LabReportecitasporfecha(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public LabReportecitasporfecha rename(String name) {
        return new LabReportecitasporfecha(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public LabReportecitasporfecha rename(Name name) {
        return new LabReportecitasporfecha(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, LocalDate, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public LabReportecitasporfecha call() {
        LabReportecitasporfecha result = new LabReportecitasporfecha(DSL.name("lab_reportecitasporfecha"), null, new Field[] {});

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
