/*
 * This file is generated by jOOQ.
 */
package me.astridcortez.hispatologialab.core.db;


import me.astridcortez.hispatologialab.core.db.tables.LabMedicamento;
import me.astridcortez.hispatologialab.core.db.tables.LabPresentacionMedicamento;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lab_medicamento</code>.
     */
    public static final LabMedicamento LAB_MEDICAMENTO = LabMedicamento.LAB_MEDICAMENTO;

    /**
     * The table <code>public.lab_presentacion_medicamento</code>.
     */
    public static final LabPresentacionMedicamento LAB_PRESENTACION_MEDICAMENTO = LabPresentacionMedicamento.LAB_PRESENTACION_MEDICAMENTO;
}
