package histopatologialab.core;

public enum RequestAction {
    CREAR, MODIFICAR, DAR_BAJA, LISTAR_JSON, VER_JSON, DEFAULT, BUSCAR, CAMBIO_ESTADO, REINICIO_PSW,SALIR, CAMBIO, CAMBIO_PSW, VER, GUARDAR_INFORME, DESCARGAR_INFORME
}
