/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db;


import histopatologialab.core.db.tables.LabDiagnostico;
import histopatologialab.core.db.tables.LabEnfermedadSistemica;
import histopatologialab.core.db.tables.LabEnfsistemicaListar;
import histopatologialab.core.db.tables.LabExamen;
import histopatologialab.core.db.tables.LabExamenBiopsia;
import histopatologialab.core.db.tables.LabExamenCaracteristica;
import histopatologialab.core.db.tables.LabExamenDiagnostico;
import histopatologialab.core.db.tables.LabExamenEnfermedadSistemica;
import histopatologialab.core.db.tables.LabExamenFrote;
import histopatologialab.core.db.tables.LabExamenHistEstados;
import histopatologialab.core.db.tables.LabExamenImagen;
import histopatologialab.core.db.tables.LabExamenReceta;
import histopatologialab.core.db.tables.LabExamenSeguimiento;
import histopatologialab.core.db.tables.LabInforme;
import histopatologialab.core.db.tables.LabMedicamento;
import histopatologialab.core.db.tables.LabPaciente;
import histopatologialab.core.db.tables.LabPresentacionMedicamento;
import histopatologialab.core.db.tables.LabRepcitasxfecha;
import histopatologialab.core.db.tables.LabReporteExamenVw;
import histopatologialab.core.db.tables.LabReportecitasporfecha;
import histopatologialab.core.db.tables.LabTincion;
import histopatologialab.core.db.tables.LabTipoOpcionLesion;
import histopatologialab.core.db.tables.LabUsuario;
import histopatologialab.core.db.tables.records.LabEnfsistemicaListarRecord;
import histopatologialab.core.db.tables.records.LabRepcitasxfechaRecord;
import histopatologialab.core.db.tables.records.LabReportecitasporfechaRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.lab_diagnostico</code>.
     */
    public final LabDiagnostico LAB_DIAGNOSTICO = LabDiagnostico.LAB_DIAGNOSTICO;

    /**
     * The table <code>public.lab_enfermedad_sistemica</code>.
     */
    public final LabEnfermedadSistemica LAB_ENFERMEDAD_SISTEMICA = LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA;

    /**
     * The table <code>public.lab_enfsistemica_listar</code>.
     */
    public final LabEnfsistemicaListar LAB_ENFSISTEMICA_LISTAR = LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR;

    /**
     * Call <code>public.lab_enfsistemica_listar</code>.
     */
    public static Result<LabEnfsistemicaListarRecord> LAB_ENFSISTEMICA_LISTAR(
          Configuration configuration
    ) {
        return configuration.dsl().selectFrom(histopatologialab.core.db.tables.LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.call(
        )).fetch();
    }

    /**
     * Get <code>public.lab_enfsistemica_listar</code> as a table.
     */
    public static LabEnfsistemicaListar LAB_ENFSISTEMICA_LISTAR() {
        return histopatologialab.core.db.tables.LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.call(
        );
    }

    /**
     * The table <code>public.lab_examen</code>.
     */
    public final LabExamen LAB_EXAMEN = LabExamen.LAB_EXAMEN;

    /**
     * The table <code>public.lab_examen_biopsia</code>.
     */
    public final LabExamenBiopsia LAB_EXAMEN_BIOPSIA = LabExamenBiopsia.LAB_EXAMEN_BIOPSIA;

    /**
     * The table <code>public.lab_examen_caracteristica</code>.
     */
    public final LabExamenCaracteristica LAB_EXAMEN_CARACTERISTICA = LabExamenCaracteristica.LAB_EXAMEN_CARACTERISTICA;

    /**
     * The table <code>public.lab_examen_diagnostico</code>.
     */
    public final LabExamenDiagnostico LAB_EXAMEN_DIAGNOSTICO = LabExamenDiagnostico.LAB_EXAMEN_DIAGNOSTICO;

    /**
     * The table <code>public.lab_examen_enfermedad_sistemica</code>.
     */
    public final LabExamenEnfermedadSistemica LAB_EXAMEN_ENFERMEDAD_SISTEMICA = LabExamenEnfermedadSistemica.LAB_EXAMEN_ENFERMEDAD_SISTEMICA;

    /**
     * The table <code>public.lab_examen_frote</code>.
     */
    public final LabExamenFrote LAB_EXAMEN_FROTE = LabExamenFrote.LAB_EXAMEN_FROTE;

    /**
     * The table <code>public.lab_examen_hist_estados</code>.
     */
    public final LabExamenHistEstados LAB_EXAMEN_HIST_ESTADOS = LabExamenHistEstados.LAB_EXAMEN_HIST_ESTADOS;

    /**
     * The table <code>public.lab_examen_imagen</code>.
     */
    public final LabExamenImagen LAB_EXAMEN_IMAGEN = LabExamenImagen.LAB_EXAMEN_IMAGEN;

    /**
     * The table <code>public.lab_examen_receta</code>.
     */
    public final LabExamenReceta LAB_EXAMEN_RECETA = LabExamenReceta.LAB_EXAMEN_RECETA;

    /**
     * The table <code>public.lab_examen_seguimiento</code>.
     */
    public final LabExamenSeguimiento LAB_EXAMEN_SEGUIMIENTO = LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO;

    /**
     * The table <code>public.lab_informe</code>.
     */
    public final LabInforme LAB_INFORME = LabInforme.LAB_INFORME;

    /**
     * The table <code>public.lab_medicamento</code>.
     */
    public final LabMedicamento LAB_MEDICAMENTO = LabMedicamento.LAB_MEDICAMENTO;

    /**
     * The table <code>public.lab_paciente</code>.
     */
    public final LabPaciente LAB_PACIENTE = LabPaciente.LAB_PACIENTE;

    /**
     * The table <code>public.lab_presentacion_medicamento</code>.
     */
    public final LabPresentacionMedicamento LAB_PRESENTACION_MEDICAMENTO = LabPresentacionMedicamento.LAB_PRESENTACION_MEDICAMENTO;

    /**
     * The table <code>public.lab_repcitasxfecha</code>.
     */
    public final LabRepcitasxfecha LAB_REPCITASXFECHA = LabRepcitasxfecha.LAB_REPCITASXFECHA;

    /**
     * Call <code>public.lab_repcitasxfecha</code>.
     */
    public static Result<LabRepcitasxfechaRecord> LAB_REPCITASXFECHA(
          Configuration configuration
        , LocalDate fechainicio
        , LocalDate fechafin
    ) {
        return configuration.dsl().selectFrom(histopatologialab.core.db.tables.LabRepcitasxfecha.LAB_REPCITASXFECHA.call(
              fechainicio
            , fechafin
        )).fetch();
    }

    /**
     * Get <code>public.lab_repcitasxfecha</code> as a table.
     */
    public static LabRepcitasxfecha LAB_REPCITASXFECHA(
          LocalDate fechainicio
        , LocalDate fechafin
    ) {
        return histopatologialab.core.db.tables.LabRepcitasxfecha.LAB_REPCITASXFECHA.call(
              fechainicio
            , fechafin
        );
    }

    /**
     * Get <code>public.lab_repcitasxfecha</code> as a table.
     */
    public static LabRepcitasxfecha LAB_REPCITASXFECHA(
          Field<LocalDate> fechainicio
        , Field<LocalDate> fechafin
    ) {
        return histopatologialab.core.db.tables.LabRepcitasxfecha.LAB_REPCITASXFECHA.call(
              fechainicio
            , fechafin
        );
    }

    /**
     * The table <code>public.lab_reporte_examen_vw</code>.
     */
    public final LabReporteExamenVw LAB_REPORTE_EXAMEN_VW = LabReporteExamenVw.LAB_REPORTE_EXAMEN_VW;

    /**
     * The table <code>public.lab_reportecitasporfecha</code>.
     */
    public final LabReportecitasporfecha LAB_REPORTECITASPORFECHA = LabReportecitasporfecha.LAB_REPORTECITASPORFECHA;

    /**
     * Call <code>public.lab_reportecitasporfecha</code>.
     */
    public static Result<LabReportecitasporfechaRecord> LAB_REPORTECITASPORFECHA(
          Configuration configuration
    ) {
        return configuration.dsl().selectFrom(histopatologialab.core.db.tables.LabReportecitasporfecha.LAB_REPORTECITASPORFECHA.call(
        )).fetch();
    }

    /**
     * Get <code>public.lab_reportecitasporfecha</code> as a table.
     */
    public static LabReportecitasporfecha LAB_REPORTECITASPORFECHA() {
        return histopatologialab.core.db.tables.LabReportecitasporfecha.LAB_REPORTECITASPORFECHA.call(
        );
    }

    /**
     * The table <code>public.lab_tincion</code>.
     */
    public final LabTincion LAB_TINCION = LabTincion.LAB_TINCION;

    /**
     * The table <code>public.lab_tipo_opcion_lesion</code>.
     */
    public final LabTipoOpcionLesion LAB_TIPO_OPCION_LESION = LabTipoOpcionLesion.LAB_TIPO_OPCION_LESION;

    /**
     * The table <code>public.lab_usuario</code>.
     */
    public final LabUsuario LAB_USUARIO = LabUsuario.LAB_USUARIO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LAB_DIAGNOSTICO_SEQ,
            Sequences.LAB_ENFERMEDAD_SISTEMICA_SEQ,
            Sequences.LAB_EXAMEN_BIOPSIA_COD_BIOPSIA_SEQ,
            Sequences.LAB_EXAMEN_BIOPSIA_COD_BIOPSIA_SEQ1,
            Sequences.LAB_EXAMEN_CARACTERISTICA_COD_EXAMEN_SEQ,
            Sequences.LAB_EXAMEN_CARACTERISTICA_COD_EXAMEN_SEQ1,
            Sequences.LAB_EXAMEN_COD_EXAMEN_SEQ,
            Sequences.LAB_EXAMEN_COD_EXAMEN_SEQ1,
            Sequences.LAB_EXAMEN_FROTE_COD_FROTE_SEQ,
            Sequences.LAB_EXAMEN_RECETA_COD_RECETA_SEQ,
            Sequences.LAB_EXAMEN_SEGUIMIENTO_COD_SEGUIMIENTO_SEQ,
            Sequences.LAB_INFORME_COD_INFORME_SEQ,
            Sequences.LAB_MEDICAMENTO_SEQ,
            Sequences.LAB_PACIENTE_SEQ,
            Sequences.LAB_PRESENTACION_MEDICAMENTO_COD_PRESENTACION_SEQ,
            Sequences.LAB_TINCION_SEQ,
            Sequences.LAB_TIPO_OPCION_LESION_SEQ,
            Sequences.LAB_USUARIO_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            LabDiagnostico.LAB_DIAGNOSTICO,
            LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA,
            LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR,
            LabExamen.LAB_EXAMEN,
            LabExamenBiopsia.LAB_EXAMEN_BIOPSIA,
            LabExamenCaracteristica.LAB_EXAMEN_CARACTERISTICA,
            LabExamenDiagnostico.LAB_EXAMEN_DIAGNOSTICO,
            LabExamenEnfermedadSistemica.LAB_EXAMEN_ENFERMEDAD_SISTEMICA,
            LabExamenFrote.LAB_EXAMEN_FROTE,
            LabExamenHistEstados.LAB_EXAMEN_HIST_ESTADOS,
            LabExamenImagen.LAB_EXAMEN_IMAGEN,
            LabExamenReceta.LAB_EXAMEN_RECETA,
            LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO,
            LabInforme.LAB_INFORME,
            LabMedicamento.LAB_MEDICAMENTO,
            LabPaciente.LAB_PACIENTE,
            LabPresentacionMedicamento.LAB_PRESENTACION_MEDICAMENTO,
            LabRepcitasxfecha.LAB_REPCITASXFECHA,
            LabReporteExamenVw.LAB_REPORTE_EXAMEN_VW,
            LabReportecitasporfecha.LAB_REPORTECITASPORFECHA,
            LabTincion.LAB_TINCION,
            LabTipoOpcionLesion.LAB_TIPO_OPCION_LESION,
            LabUsuario.LAB_USUARIO);
    }
}
