/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db;


import java.util.Arrays;
import java.util.List;

import histopatologialab.core.db.tables.LabMedicamento;
import histopatologialab.core.db.tables.LabPresentacionMedicamento;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.lab_medicamento</code>.
     */
    public final LabMedicamento LAB_MEDICAMENTO = LabMedicamento.LAB_MEDICAMENTO;

    /**
     * The table <code>public.lab_presentacion_medicamento</code>.
     */
    public final LabPresentacionMedicamento LAB_PRESENTACION_MEDICAMENTO = LabPresentacionMedicamento.LAB_PRESENTACION_MEDICAMENTO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LAB_MEDICAMENTO_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            LabMedicamento.LAB_MEDICAMENTO,
            LabPresentacionMedicamento.LAB_PRESENTACION_MEDICAMENTO);
    }
}
