/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db;


import histopatologialab.core.db.tables.LabEnfsistemicaListar;
import histopatologialab.core.db.tables.LabRepcitasxfecha;
import histopatologialab.core.db.tables.LabReportecitasporfecha;
import histopatologialab.core.db.tables.records.LabEnfsistemicaListarRecord;
import histopatologialab.core.db.tables.records.LabRepcitasxfechaRecord;
import histopatologialab.core.db.tables.records.LabReportecitasporfechaRecord;

import java.time.LocalDate;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.lab_enfsistemica_listar</code>.
     */
    public static Result<LabEnfsistemicaListarRecord> labEnfsistemicaListar(
          Configuration configuration
    ) {
        return configuration.dsl().selectFrom(histopatologialab.core.db.tables.LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.call(
        )).fetch();
    }

    /**
     * Get <code>public.lab_enfsistemica_listar</code> as a table.
     */
    public static LabEnfsistemicaListar labEnfsistemicaListar() {
        return histopatologialab.core.db.tables.LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.call(
        );
    }

    /**
     * Call <code>public.lab_repcitasxfecha</code>.
     */
    public static Result<LabRepcitasxfechaRecord> labRepcitasxfecha(
          Configuration configuration
        , LocalDate fechainicio
        , LocalDate fechafin
    ) {
        return configuration.dsl().selectFrom(histopatologialab.core.db.tables.LabRepcitasxfecha.LAB_REPCITASXFECHA.call(
              fechainicio
            , fechafin
        )).fetch();
    }

    /**
     * Get <code>public.lab_repcitasxfecha</code> as a table.
     */
    public static LabRepcitasxfecha labRepcitasxfecha(
          LocalDate fechainicio
        , LocalDate fechafin
    ) {
        return histopatologialab.core.db.tables.LabRepcitasxfecha.LAB_REPCITASXFECHA.call(
              fechainicio
            , fechafin
        );
    }

    /**
     * Get <code>public.lab_repcitasxfecha</code> as a table.
     */
    public static LabRepcitasxfecha labRepcitasxfecha(
          Field<LocalDate> fechainicio
        , Field<LocalDate> fechafin
    ) {
        return histopatologialab.core.db.tables.LabRepcitasxfecha.LAB_REPCITASXFECHA.call(
              fechainicio
            , fechafin
        );
    }

    /**
     * Call <code>public.lab_reportecitasporfecha</code>.
     */
    public static Result<LabReportecitasporfechaRecord> labReportecitasporfecha(
          Configuration configuration
    ) {
        return configuration.dsl().selectFrom(histopatologialab.core.db.tables.LabReportecitasporfecha.LAB_REPORTECITASPORFECHA.call(
        )).fetch();
    }

    /**
     * Get <code>public.lab_reportecitasporfecha</code> as a table.
     */
    public static LabReportecitasporfecha labReportecitasporfecha() {
        return histopatologialab.core.db.tables.LabReportecitasporfecha.LAB_REPORTECITASPORFECHA.call(
        );
    }
}
