/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.lab_enfermedad_sistematica_cod_enfermedad_sistematica_seq</code>
     */
    public static final Sequence<Integer> LAB_ENFERMEDAD_SISTEMATICA_COD_ENFERMEDAD_SISTEMATICA_SEQ = Internal.createSequence("lab_enfermedad_sistematica_cod_enfermedad_sistematica_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_examen_biopsia_cod_biopsia_seq</code>
     */
    public static final Sequence<Integer> LAB_EXAMEN_BIOPSIA_COD_BIOPSIA_SEQ = Internal.createSequence("lab_examen_biopsia_cod_biopsia_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_examen_caracteristica_cod_examen_seq</code>
     */
    public static final Sequence<Integer> LAB_EXAMEN_CARACTERISTICA_COD_EXAMEN_SEQ = Internal.createSequence("lab_examen_caracteristica_cod_examen_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_examen_cod_examen_seq</code>
     */
    public static final Sequence<Integer> LAB_EXAMEN_COD_EXAMEN_SEQ = Internal.createSequence("lab_examen_cod_examen_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_funcion_codigo_funcion_seq</code>
     */
    public static final Sequence<Integer> LAB_FUNCION_CODIGO_FUNCION_SEQ = Internal.createSequence("lab_funcion_codigo_funcion_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_medicamento_seq</code>
     */
    public static final Sequence<Long> LAB_MEDICAMENTO_SEQ = Internal.createSequence("lab_medicamento_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_paciente_seq</code>
     */
    public static final Sequence<Long> LAB_PACIENTE_SEQ = Internal.createSequence("lab_paciente_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_rol_codigo_rol_seq</code>
     */
    public static final Sequence<Integer> LAB_ROL_CODIGO_ROL_SEQ = Internal.createSequence("lab_rol_codigo_rol_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_tipo_opcion_lesion_cod_tipo_opcion_lesion_seq</code>
     */
    public static final Sequence<Integer> LAB_TIPO_OPCION_LESION_COD_TIPO_OPCION_LESION_SEQ = Internal.createSequence("lab_tipo_opcion_lesion_cod_tipo_opcion_lesion_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.lab_usuario_codigo_usuario_seq</code>
     */
    public static final Sequence<Integer> LAB_USUARIO_CODIGO_USUARIO_SEQ = Internal.createSequence("lab_usuario_codigo_usuario_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
