/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db;


import histopatologialab.core.db.tables.LabEnfermedadSistemica;
import histopatologialab.core.db.tables.LabExamen;
import histopatologialab.core.db.tables.LabExamenBiopsia;
import histopatologialab.core.db.tables.LabExamenCaracteristica;
import histopatologialab.core.db.tables.LabExamenEnfermedadSistematica;
import histopatologialab.core.db.tables.LabFuncion;
import histopatologialab.core.db.tables.LabMedicamento;
import histopatologialab.core.db.tables.LabPaciente;
import histopatologialab.core.db.tables.LabPresentacionMedicamento;
import histopatologialab.core.db.tables.LabRol;
import histopatologialab.core.db.tables.LabRolFuncion;
import histopatologialab.core.db.tables.LabTipoOpcionLesion;
import histopatologialab.core.db.tables.LabUsuario;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lab_enfermedad_sistemica</code>.
     */
    public static final LabEnfermedadSistemica LAB_ENFERMEDAD_SISTEMICA = LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA;

    /**
     * The table <code>public.lab_examen</code>.
     */
    public static final LabExamen LAB_EXAMEN = LabExamen.LAB_EXAMEN;

    /**
     * The table <code>public.lab_examen_biopsia</code>.
     */
    public static final LabExamenBiopsia LAB_EXAMEN_BIOPSIA = LabExamenBiopsia.LAB_EXAMEN_BIOPSIA;

    /**
     * The table <code>public.lab_examen_caracteristica</code>.
     */
    public static final LabExamenCaracteristica LAB_EXAMEN_CARACTERISTICA = LabExamenCaracteristica.LAB_EXAMEN_CARACTERISTICA;

    /**
     * The table <code>public.lab_examen_enfermedad_sistematica</code>.
     */
    public static final LabExamenEnfermedadSistematica LAB_EXAMEN_ENFERMEDAD_SISTEMATICA = LabExamenEnfermedadSistematica.LAB_EXAMEN_ENFERMEDAD_SISTEMATICA;

    /**
     * The table <code>public.lab_funcion</code>.
     */
    public static final LabFuncion LAB_FUNCION = LabFuncion.LAB_FUNCION;

    /**
     * The table <code>public.lab_medicamento</code>.
     */
    public static final LabMedicamento LAB_MEDICAMENTO = LabMedicamento.LAB_MEDICAMENTO;

    /**
     * The table <code>public.lab_paciente</code>.
     */
    public static final LabPaciente LAB_PACIENTE = LabPaciente.LAB_PACIENTE;

    /**
     * The table <code>public.lab_presentacion_medicamento</code>.
     */
    public static final LabPresentacionMedicamento LAB_PRESENTACION_MEDICAMENTO = LabPresentacionMedicamento.LAB_PRESENTACION_MEDICAMENTO;

    /**
     * The table <code>public.lab_rol</code>.
     */
    public static final LabRol LAB_ROL = LabRol.LAB_ROL;

    /**
     * The table <code>public.lab_rol_funcion</code>.
     */
    public static final LabRolFuncion LAB_ROL_FUNCION = LabRolFuncion.LAB_ROL_FUNCION;

    /**
     * The table <code>public.lab_tipo_opcion_lesion</code>.
     */
    public static final LabTipoOpcionLesion LAB_TIPO_OPCION_LESION = LabTipoOpcionLesion.LAB_TIPO_OPCION_LESION;

    /**
     * The table <code>public.lab_usuario</code>.
     */
    public static final LabUsuario LAB_USUARIO = LabUsuario.LAB_USUARIO;
}
