/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.CrmPersona;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrmPersonaRecord extends UpdatableRecordImpl<CrmPersonaRecord> implements Record10<Integer, String, String, String, String, String, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.crm_persona.pe_persona</code>.
     */
    public void setPePersona(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_persona</code>.
     */
    public Integer getPePersona() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.crm_persona.pe_identificacion</code>.
     */
    public void setPeIdentificacion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_identificacion</code>.
     */
    public String getPeIdentificacion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.crm_persona.pe_nombre</code>.
     */
    public void setPeNombre(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_nombre</code>.
     */
    public String getPeNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.crm_persona.pe_direccion</code>.
     */
    public void setPeDireccion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_direccion</code>.
     */
    public String getPeDireccion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.crm_persona.pe_telefono</code>.
     */
    public void setPeTelefono(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_telefono</code>.
     */
    public String getPeTelefono() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.crm_persona.pe_estadocivil</code>.
     */
    public void setPeEstadocivil(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_estadocivil</code>.
     */
    public String getPeEstadocivil() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.crm_persona.pe_fechanacimiento</code>.
     */
    public void setPeFechanacimiento(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_fechanacimiento</code>.
     */
    public LocalDateTime getPeFechanacimiento() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.crm_persona.pe_genero</code>.
     */
    public void setPeGenero(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_genero</code>.
     */
    public String getPeGenero() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.crm_persona.pe_ocupacion</code>.
     */
    public void setPeOcupacion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_ocupacion</code>.
     */
    public String getPeOcupacion() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.crm_persona.pe_tipo_identificacion</code>.
     */
    public void setPeTipoIdentificacion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.crm_persona.pe_tipo_identificacion</code>.
     */
    public String getPeTipoIdentificacion() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, LocalDateTime, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, String, LocalDateTime, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CrmPersona.CRM_PERSONA.PE_PERSONA;
    }

    @Override
    public Field<String> field2() {
        return CrmPersona.CRM_PERSONA.PE_IDENTIFICACION;
    }

    @Override
    public Field<String> field3() {
        return CrmPersona.CRM_PERSONA.PE_NOMBRE;
    }

    @Override
    public Field<String> field4() {
        return CrmPersona.CRM_PERSONA.PE_DIRECCION;
    }

    @Override
    public Field<String> field5() {
        return CrmPersona.CRM_PERSONA.PE_TELEFONO;
    }

    @Override
    public Field<String> field6() {
        return CrmPersona.CRM_PERSONA.PE_ESTADOCIVIL;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return CrmPersona.CRM_PERSONA.PE_FECHANACIMIENTO;
    }

    @Override
    public Field<String> field8() {
        return CrmPersona.CRM_PERSONA.PE_GENERO;
    }

    @Override
    public Field<String> field9() {
        return CrmPersona.CRM_PERSONA.PE_OCUPACION;
    }

    @Override
    public Field<String> field10() {
        return CrmPersona.CRM_PERSONA.PE_TIPO_IDENTIFICACION;
    }

    @Override
    public Integer component1() {
        return getPePersona();
    }

    @Override
    public String component2() {
        return getPeIdentificacion();
    }

    @Override
    public String component3() {
        return getPeNombre();
    }

    @Override
    public String component4() {
        return getPeDireccion();
    }

    @Override
    public String component5() {
        return getPeTelefono();
    }

    @Override
    public String component6() {
        return getPeEstadocivil();
    }

    @Override
    public LocalDateTime component7() {
        return getPeFechanacimiento();
    }

    @Override
    public String component8() {
        return getPeGenero();
    }

    @Override
    public String component9() {
        return getPeOcupacion();
    }

    @Override
    public String component10() {
        return getPeTipoIdentificacion();
    }

    @Override
    public Integer value1() {
        return getPePersona();
    }

    @Override
    public String value2() {
        return getPeIdentificacion();
    }

    @Override
    public String value3() {
        return getPeNombre();
    }

    @Override
    public String value4() {
        return getPeDireccion();
    }

    @Override
    public String value5() {
        return getPeTelefono();
    }

    @Override
    public String value6() {
        return getPeEstadocivil();
    }

    @Override
    public LocalDateTime value7() {
        return getPeFechanacimiento();
    }

    @Override
    public String value8() {
        return getPeGenero();
    }

    @Override
    public String value9() {
        return getPeOcupacion();
    }

    @Override
    public String value10() {
        return getPeTipoIdentificacion();
    }

    @Override
    public CrmPersonaRecord value1(Integer value) {
        setPePersona(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value2(String value) {
        setPeIdentificacion(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value3(String value) {
        setPeNombre(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value4(String value) {
        setPeDireccion(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value5(String value) {
        setPeTelefono(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value6(String value) {
        setPeEstadocivil(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value7(LocalDateTime value) {
        setPeFechanacimiento(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value8(String value) {
        setPeGenero(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value9(String value) {
        setPeOcupacion(value);
        return this;
    }

    @Override
    public CrmPersonaRecord value10(String value) {
        setPeTipoIdentificacion(value);
        return this;
    }

    @Override
    public CrmPersonaRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, LocalDateTime value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrmPersonaRecord
     */
    public CrmPersonaRecord() {
        super(CrmPersona.CRM_PERSONA);
    }

    /**
     * Create a detached, initialised CrmPersonaRecord
     */
    public CrmPersonaRecord(Integer pePersona, String peIdentificacion, String peNombre, String peDireccion, String peTelefono, String peEstadocivil, LocalDateTime peFechanacimiento, String peGenero, String peOcupacion, String peTipoIdentificacion) {
        super(CrmPersona.CRM_PERSONA);

        setPePersona(pePersona);
        setPeIdentificacion(peIdentificacion);
        setPeNombre(peNombre);
        setPeDireccion(peDireccion);
        setPeTelefono(peTelefono);
        setPeEstadocivil(peEstadocivil);
        setPeFechanacimiento(peFechanacimiento);
        setPeGenero(peGenero);
        setPeOcupacion(peOcupacion);
        setPeTipoIdentificacion(peTipoIdentificacion);
    }
}
