/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabExamenSeguimiento;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabExamenSeguimientoRecord extends UpdatableRecordImpl<LabExamenSeguimientoRecord> implements Record8<Integer, Integer, LocalDate, String, String, Long, Long, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_examen_seguimiento.cod_seguimiento</code>.
     */
    public void setCodSeguimiento(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.cod_seguimiento</code>.
     */
    public Integer getCodSeguimiento() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.cod_examen</code>.
     */
    public void setCodExamen(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.cod_examen</code>.
     */
    public Integer getCodExamen() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.fecha_seguimiento</code>.
     */
    public void setFechaSeguimiento(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.fecha_seguimiento</code>.
     */
    public LocalDate getFechaSeguimiento() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.observaciones</code>.
     */
    public void setObservaciones(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.observaciones</code>.
     */
    public String getObservaciones() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.observaciones_adicional</code>.
     */
    public void setObservacionesAdicional(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.observaciones_adicional</code>.
     */
    public String getObservacionesAdicional() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.usuario_seguimiento</code>.
     */
    public void setUsuarioSeguimiento(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.usuario_seguimiento</code>.
     */
    public Long getUsuarioSeguimiento() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.modificado_por</code>.
     */
    public void setModificadoPor(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.modificado_por</code>.
     */
    public Long getModificadoPor() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.lab_examen_seguimiento.fecha_modificacion</code>.
     */
    public void setFechaModificacion(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lab_examen_seguimiento.fecha_modificacion</code>.
     */
    public LocalDate getFechaModificacion() {
        return (LocalDate) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, LocalDate, String, String, Long, Long, LocalDate> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, LocalDate, String, String, Long, Long, LocalDate> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.COD_SEGUIMIENTO;
    }

    @Override
    public Field<Integer> field2() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.COD_EXAMEN;
    }

    @Override
    public Field<LocalDate> field3() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.FECHA_SEGUIMIENTO;
    }

    @Override
    public Field<String> field4() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.OBSERVACIONES;
    }

    @Override
    public Field<String> field5() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.OBSERVACIONES_ADICIONAL;
    }

    @Override
    public Field<Long> field6() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.USUARIO_SEGUIMIENTO;
    }

    @Override
    public Field<Long> field7() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.MODIFICADO_POR;
    }

    @Override
    public Field<LocalDate> field8() {
        return LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO.FECHA_MODIFICACION;
    }

    @Override
    public Integer component1() {
        return getCodSeguimiento();
    }

    @Override
    public Integer component2() {
        return getCodExamen();
    }

    @Override
    public LocalDate component3() {
        return getFechaSeguimiento();
    }

    @Override
    public String component4() {
        return getObservaciones();
    }

    @Override
    public String component5() {
        return getObservacionesAdicional();
    }

    @Override
    public Long component6() {
        return getUsuarioSeguimiento();
    }

    @Override
    public Long component7() {
        return getModificadoPor();
    }

    @Override
    public LocalDate component8() {
        return getFechaModificacion();
    }

    @Override
    public Integer value1() {
        return getCodSeguimiento();
    }

    @Override
    public Integer value2() {
        return getCodExamen();
    }

    @Override
    public LocalDate value3() {
        return getFechaSeguimiento();
    }

    @Override
    public String value4() {
        return getObservaciones();
    }

    @Override
    public String value5() {
        return getObservacionesAdicional();
    }

    @Override
    public Long value6() {
        return getUsuarioSeguimiento();
    }

    @Override
    public Long value7() {
        return getModificadoPor();
    }

    @Override
    public LocalDate value8() {
        return getFechaModificacion();
    }

    @Override
    public LabExamenSeguimientoRecord value1(Integer value) {
        setCodSeguimiento(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value2(Integer value) {
        setCodExamen(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value3(LocalDate value) {
        setFechaSeguimiento(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value4(String value) {
        setObservaciones(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value5(String value) {
        setObservacionesAdicional(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value6(Long value) {
        setUsuarioSeguimiento(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value7(Long value) {
        setModificadoPor(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord value8(LocalDate value) {
        setFechaModificacion(value);
        return this;
    }

    @Override
    public LabExamenSeguimientoRecord values(Integer value1, Integer value2, LocalDate value3, String value4, String value5, Long value6, Long value7, LocalDate value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabExamenSeguimientoRecord
     */
    public LabExamenSeguimientoRecord() {
        super(LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO);
    }

    /**
     * Create a detached, initialised LabExamenSeguimientoRecord
     */
    public LabExamenSeguimientoRecord(Integer codSeguimiento, Integer codExamen, LocalDate fechaSeguimiento, String observaciones, String observacionesAdicional, Long usuarioSeguimiento, Long modificadoPor, LocalDate fechaModificacion) {
        super(LabExamenSeguimiento.LAB_EXAMEN_SEGUIMIENTO);

        setCodSeguimiento(codSeguimiento);
        setCodExamen(codExamen);
        setFechaSeguimiento(fechaSeguimiento);
        setObservaciones(observaciones);
        setObservacionesAdicional(observacionesAdicional);
        setUsuarioSeguimiento(usuarioSeguimiento);
        setModificadoPor(modificadoPor);
        setFechaModificacion(fechaModificacion);
    }
}
