/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabEnfermedadSistemica;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabEnfermedadSistemicaRecord extends UpdatableRecordImpl<LabEnfermedadSistemicaRecord> implements Record7<Integer, String, String, LocalDate, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.cod_enfermedad_sistemica</code>.
     */
    public void setCodEnfermedadSistemica(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.cod_enfermedad_sistemica</code>.
     */
    public Integer getCodEnfermedadSistemica() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.nombre_enfermedad</code>.
     */
    public void setNombreEnfermedad(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.nombre_enfermedad</code>.
     */
    public String getNombreEnfermedad() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.estado_enfermedad</code>.
     */
    public void setEstadoEnfermedad(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.estado_enfermedad</code>.
     */
    public String getEstadoEnfermedad() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.fecha_creacion</code>.
     */
    public void setFechaCreacion(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.fecha_creacion</code>.
     */
    public LocalDate getFechaCreacion() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.creado_por</code>.
     */
    public void setCreadoPor(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.creado_por</code>.
     */
    public String getCreadoPor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.modificado_por</code>.
     */
    public void setModificadoPor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.modificado_por</code>.
     */
    public String getModificadoPor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lab_enfermedad_sistemica.fecha_modificacion</code>.
     */
    public void setFechaModificacion(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_enfermedad_sistemica.fecha_modificacion</code>.
     */
    public LocalDate getFechaModificacion() {
        return (LocalDate) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, LocalDate, String, String, LocalDate> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, LocalDate, String, String, LocalDate> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.COD_ENFERMEDAD_SISTEMICA;
    }

    @Override
    public Field<String> field2() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.NOMBRE_ENFERMEDAD;
    }

    @Override
    public Field<String> field3() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.ESTADO_ENFERMEDAD;
    }

    @Override
    public Field<LocalDate> field4() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.FECHA_CREACION;
    }

    @Override
    public Field<String> field5() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.CREADO_POR;
    }

    @Override
    public Field<String> field6() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.MODIFICADO_POR;
    }

    @Override
    public Field<LocalDate> field7() {
        return LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA.FECHA_MODIFICACION;
    }

    @Override
    public Integer component1() {
        return getCodEnfermedadSistemica();
    }

    @Override
    public String component2() {
        return getNombreEnfermedad();
    }

    @Override
    public String component3() {
        return getEstadoEnfermedad();
    }

    @Override
    public LocalDate component4() {
        return getFechaCreacion();
    }

    @Override
    public String component5() {
        return getCreadoPor();
    }

    @Override
    public String component6() {
        return getModificadoPor();
    }

    @Override
    public LocalDate component7() {
        return getFechaModificacion();
    }

    @Override
    public Integer value1() {
        return getCodEnfermedadSistemica();
    }

    @Override
    public String value2() {
        return getNombreEnfermedad();
    }

    @Override
    public String value3() {
        return getEstadoEnfermedad();
    }

    @Override
    public LocalDate value4() {
        return getFechaCreacion();
    }

    @Override
    public String value5() {
        return getCreadoPor();
    }

    @Override
    public String value6() {
        return getModificadoPor();
    }

    @Override
    public LocalDate value7() {
        return getFechaModificacion();
    }

    @Override
    public LabEnfermedadSistemicaRecord value1(Integer value) {
        setCodEnfermedadSistemica(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord value2(String value) {
        setNombreEnfermedad(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord value3(String value) {
        setEstadoEnfermedad(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord value4(LocalDate value) {
        setFechaCreacion(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord value5(String value) {
        setCreadoPor(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord value6(String value) {
        setModificadoPor(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord value7(LocalDate value) {
        setFechaModificacion(value);
        return this;
    }

    @Override
    public LabEnfermedadSistemicaRecord values(Integer value1, String value2, String value3, LocalDate value4, String value5, String value6, LocalDate value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabEnfermedadSistemicaRecord
     */
    public LabEnfermedadSistemicaRecord() {
        super(LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA);
    }

    /**
     * Create a detached, initialised LabEnfermedadSistemicaRecord
     */
    public LabEnfermedadSistemicaRecord(Integer codEnfermedadSistemica, String nombreEnfermedad, String estadoEnfermedad, LocalDate fechaCreacion, String creadoPor, String modificadoPor, LocalDate fechaModificacion) {
        super(LabEnfermedadSistemica.LAB_ENFERMEDAD_SISTEMICA);

        setCodEnfermedadSistemica(codEnfermedadSistemica);
        setNombreEnfermedad(nombreEnfermedad);
        setEstadoEnfermedad(estadoEnfermedad);
        setFechaCreacion(fechaCreacion);
        setCreadoPor(creadoPor);
        setModificadoPor(modificadoPor);
        setFechaModificacion(fechaModificacion);
    }
}
