/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabExamenReceta;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabExamenRecetaRecord extends UpdatableRecordImpl<LabExamenRecetaRecord> implements Record9<Integer, Integer, Integer, Integer, String, Long, LocalDate, Long, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_examen_receta.cod_receta</code>.
     */
    public void setCodReceta(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.cod_receta</code>.
     */
    public Integer getCodReceta() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_examen_receta.cod_examen</code>.
     */
    public void setCodExamen(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.cod_examen</code>.
     */
    public Integer getCodExamen() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.lab_examen_receta.cod_presentacion_medicamento</code>.
     */
    public void setCodPresentacionMedicamento(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.cod_presentacion_medicamento</code>.
     */
    public Integer getCodPresentacionMedicamento() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.lab_examen_receta.num_receta</code>.
     */
    public void setNumReceta(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.num_receta</code>.
     */
    public Integer getNumReceta() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.lab_examen_receta.notas</code>.
     */
    public void setNotas(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.notas</code>.
     */
    public String getNotas() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lab_examen_receta.creado_por</code>.
     */
    public void setCreadoPor(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.creado_por</code>.
     */
    public Long getCreadoPor() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.lab_examen_receta.fecha_creacion</code>.
     */
    public void setFechaCreacion(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.fecha_creacion</code>.
     */
    public LocalDate getFechaCreacion() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.lab_examen_receta.modificado_por</code>.
     */
    public void setModificadoPor(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.modificado_por</code>.
     */
    public Long getModificadoPor() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.lab_examen_receta.fecha_modificacion</code>.
     */
    public void setFechaModificacion(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lab_examen_receta.fecha_modificacion</code>.
     */
    public LocalDate getFechaModificacion() {
        return (LocalDate) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, Long, LocalDate, Long, LocalDate> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, String, Long, LocalDate, Long, LocalDate> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.COD_RECETA;
    }

    @Override
    public Field<Integer> field2() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.COD_EXAMEN;
    }

    @Override
    public Field<Integer> field3() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.COD_PRESENTACION_MEDICAMENTO;
    }

    @Override
    public Field<Integer> field4() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.NUM_RECETA;
    }

    @Override
    public Field<String> field5() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.NOTAS;
    }

    @Override
    public Field<Long> field6() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.CREADO_POR;
    }

    @Override
    public Field<LocalDate> field7() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.FECHA_CREACION;
    }

    @Override
    public Field<Long> field8() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.MODIFICADO_POR;
    }

    @Override
    public Field<LocalDate> field9() {
        return LabExamenReceta.LAB_EXAMEN_RECETA.FECHA_MODIFICACION;
    }

    @Override
    public Integer component1() {
        return getCodReceta();
    }

    @Override
    public Integer component2() {
        return getCodExamen();
    }

    @Override
    public Integer component3() {
        return getCodPresentacionMedicamento();
    }

    @Override
    public Integer component4() {
        return getNumReceta();
    }

    @Override
    public String component5() {
        return getNotas();
    }

    @Override
    public Long component6() {
        return getCreadoPor();
    }

    @Override
    public LocalDate component7() {
        return getFechaCreacion();
    }

    @Override
    public Long component8() {
        return getModificadoPor();
    }

    @Override
    public LocalDate component9() {
        return getFechaModificacion();
    }

    @Override
    public Integer value1() {
        return getCodReceta();
    }

    @Override
    public Integer value2() {
        return getCodExamen();
    }

    @Override
    public Integer value3() {
        return getCodPresentacionMedicamento();
    }

    @Override
    public Integer value4() {
        return getNumReceta();
    }

    @Override
    public String value5() {
        return getNotas();
    }

    @Override
    public Long value6() {
        return getCreadoPor();
    }

    @Override
    public LocalDate value7() {
        return getFechaCreacion();
    }

    @Override
    public Long value8() {
        return getModificadoPor();
    }

    @Override
    public LocalDate value9() {
        return getFechaModificacion();
    }

    @Override
    public LabExamenRecetaRecord value1(Integer value) {
        setCodReceta(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value2(Integer value) {
        setCodExamen(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value3(Integer value) {
        setCodPresentacionMedicamento(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value4(Integer value) {
        setNumReceta(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value5(String value) {
        setNotas(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value6(Long value) {
        setCreadoPor(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value7(LocalDate value) {
        setFechaCreacion(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value8(Long value) {
        setModificadoPor(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord value9(LocalDate value) {
        setFechaModificacion(value);
        return this;
    }

    @Override
    public LabExamenRecetaRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, Long value6, LocalDate value7, Long value8, LocalDate value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabExamenRecetaRecord
     */
    public LabExamenRecetaRecord() {
        super(LabExamenReceta.LAB_EXAMEN_RECETA);
    }

    /**
     * Create a detached, initialised LabExamenRecetaRecord
     */
    public LabExamenRecetaRecord(Integer codReceta, Integer codExamen, Integer codPresentacionMedicamento, Integer numReceta, String notas, Long creadoPor, LocalDate fechaCreacion, Long modificadoPor, LocalDate fechaModificacion) {
        super(LabExamenReceta.LAB_EXAMEN_RECETA);

        setCodReceta(codReceta);
        setCodExamen(codExamen);
        setCodPresentacionMedicamento(codPresentacionMedicamento);
        setNumReceta(numReceta);
        setNotas(notas);
        setCreadoPor(creadoPor);
        setFechaCreacion(fechaCreacion);
        setModificadoPor(modificadoPor);
        setFechaModificacion(fechaModificacion);
    }
}
