/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabEnfsistemicaListar;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabEnfsistemicaListarRecord extends TableRecordImpl<LabEnfsistemicaListarRecord> implements Record7<Integer, String, String, String, LocalDate, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_enfsistemica</code>.
     */
    public void setBEnfsistemica(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_enfsistemica</code>.
     */
    public Integer getBEnfsistemica() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_nomenfermedad</code>.
     */
    public void setBNomenfermedad(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_nomenfermedad</code>.
     */
    public String getBNomenfermedad() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_estatus_enfermedad</code>.
     */
    public void setBEstatusEnfermedad(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_estatus_enfermedad</code>.
     */
    public String getBEstatusEnfermedad() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_creadopor</code>.
     */
    public void setBCreadopor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_creadopor</code>.
     */
    public String getBCreadopor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_fechacreacion</code>.
     */
    public void setBFechacreacion(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_fechacreacion</code>.
     */
    public LocalDate getBFechacreacion() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_modificadopor</code>.
     */
    public void setBModificadopor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_modificadopor</code>.
     */
    public String getBModificadopor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lab_enfsistemica_listar.b_fecha_modif</code>.
     */
    public void setBFechaModif(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_enfsistemica_listar.b_fecha_modif</code>.
     */
    public LocalDate getBFechaModif() {
        return (LocalDate) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, LocalDate, String, LocalDate> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, LocalDate, String, LocalDate> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_ENFSISTEMICA;
    }

    @Override
    public Field<String> field2() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_NOMENFERMEDAD;
    }

    @Override
    public Field<String> field3() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_ESTATUS_ENFERMEDAD;
    }

    @Override
    public Field<String> field4() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_CREADOPOR;
    }

    @Override
    public Field<LocalDate> field5() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_FECHACREACION;
    }

    @Override
    public Field<String> field6() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_MODIFICADOPOR;
    }

    @Override
    public Field<LocalDate> field7() {
        return LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR.B_FECHA_MODIF;
    }

    @Override
    public Integer component1() {
        return getBEnfsistemica();
    }

    @Override
    public String component2() {
        return getBNomenfermedad();
    }

    @Override
    public String component3() {
        return getBEstatusEnfermedad();
    }

    @Override
    public String component4() {
        return getBCreadopor();
    }

    @Override
    public LocalDate component5() {
        return getBFechacreacion();
    }

    @Override
    public String component6() {
        return getBModificadopor();
    }

    @Override
    public LocalDate component7() {
        return getBFechaModif();
    }

    @Override
    public Integer value1() {
        return getBEnfsistemica();
    }

    @Override
    public String value2() {
        return getBNomenfermedad();
    }

    @Override
    public String value3() {
        return getBEstatusEnfermedad();
    }

    @Override
    public String value4() {
        return getBCreadopor();
    }

    @Override
    public LocalDate value5() {
        return getBFechacreacion();
    }

    @Override
    public String value6() {
        return getBModificadopor();
    }

    @Override
    public LocalDate value7() {
        return getBFechaModif();
    }

    @Override
    public LabEnfsistemicaListarRecord value1(Integer value) {
        setBEnfsistemica(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord value2(String value) {
        setBNomenfermedad(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord value3(String value) {
        setBEstatusEnfermedad(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord value4(String value) {
        setBCreadopor(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord value5(LocalDate value) {
        setBFechacreacion(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord value6(String value) {
        setBModificadopor(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord value7(LocalDate value) {
        setBFechaModif(value);
        return this;
    }

    @Override
    public LabEnfsistemicaListarRecord values(Integer value1, String value2, String value3, String value4, LocalDate value5, String value6, LocalDate value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabEnfsistemicaListarRecord
     */
    public LabEnfsistemicaListarRecord() {
        super(LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR);
    }

    /**
     * Create a detached, initialised LabEnfsistemicaListarRecord
     */
    public LabEnfsistemicaListarRecord(Integer bEnfsistemica, String bNomenfermedad, String bEstatusEnfermedad, String bCreadopor, LocalDate bFechacreacion, String bModificadopor, LocalDate bFechaModif) {
        super(LabEnfsistemicaListar.LAB_ENFSISTEMICA_LISTAR);

        setBEnfsistemica(bEnfsistemica);
        setBNomenfermedad(bNomenfermedad);
        setBEstatusEnfermedad(bEstatusEnfermedad);
        setBCreadopor(bCreadopor);
        setBFechacreacion(bFechacreacion);
        setBModificadopor(bModificadopor);
        setBFechaModif(bFechaModif);
    }
}
