/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabExamenImagen;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabExamenImagenRecord extends TableRecordImpl<LabExamenImagenRecord> implements Record10<Integer, String, String, Integer, String, String, LocalDate, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_examen_imagen.cod_examen</code>.
     */
    public void setCodExamen(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.cod_examen</code>.
     */
    public Integer getCodExamen() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.num_frote</code>.
     */
    public void setNumFrote(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.num_frote</code>.
     */
    public String getNumFrote() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.num_biopsia</code>.
     */
    public void setNumBiopsia(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.num_biopsia</code>.
     */
    public String getNumBiopsia() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.num_imagen</code>.
     */
    public void setNumImagen(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.num_imagen</code>.
     */
    public Integer getNumImagen() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.ruta_imagen</code>.
     */
    public void setRutaImagen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.ruta_imagen</code>.
     */
    public String getRutaImagen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.nombre_imagen</code>.
     */
    public void setNombreImagen(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.nombre_imagen</code>.
     */
    public String getNombreImagen() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.fecha_creacion</code>.
     */
    public void setFechaCreacion(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.fecha_creacion</code>.
     */
    public LocalDate getFechaCreacion() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.creado_por</code>.
     */
    public void setCreadoPor(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.creado_por</code>.
     */
    public String getCreadoPor() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.modificado_por</code>.
     */
    public void setModificadoPor(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.modificado_por</code>.
     */
    public String getModificadoPor() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.lab_examen_imagen.fecha_modificacion</code>.
     */
    public void setFechaModificacion(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.lab_examen_imagen.fecha_modificacion</code>.
     */
    public LocalDate getFechaModificacion() {
        return (LocalDate) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, Integer, String, String, LocalDate, String, String, LocalDate> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, Integer, String, String, LocalDate, String, String, LocalDate> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.COD_EXAMEN;
    }

    @Override
    public Field<String> field2() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.NUM_FROTE;
    }

    @Override
    public Field<String> field3() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.NUM_BIOPSIA;
    }

    @Override
    public Field<Integer> field4() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.NUM_IMAGEN;
    }

    @Override
    public Field<String> field5() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.RUTA_IMAGEN;
    }

    @Override
    public Field<String> field6() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.NOMBRE_IMAGEN;
    }

    @Override
    public Field<LocalDate> field7() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.FECHA_CREACION;
    }

    @Override
    public Field<String> field8() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.CREADO_POR;
    }

    @Override
    public Field<String> field9() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.MODIFICADO_POR;
    }

    @Override
    public Field<LocalDate> field10() {
        return LabExamenImagen.LAB_EXAMEN_IMAGEN.FECHA_MODIFICACION;
    }

    @Override
    public Integer component1() {
        return getCodExamen();
    }

    @Override
    public String component2() {
        return getNumFrote();
    }

    @Override
    public String component3() {
        return getNumBiopsia();
    }

    @Override
    public Integer component4() {
        return getNumImagen();
    }

    @Override
    public String component5() {
        return getRutaImagen();
    }

    @Override
    public String component6() {
        return getNombreImagen();
    }

    @Override
    public LocalDate component7() {
        return getFechaCreacion();
    }

    @Override
    public String component8() {
        return getCreadoPor();
    }

    @Override
    public String component9() {
        return getModificadoPor();
    }

    @Override
    public LocalDate component10() {
        return getFechaModificacion();
    }

    @Override
    public Integer value1() {
        return getCodExamen();
    }

    @Override
    public String value2() {
        return getNumFrote();
    }

    @Override
    public String value3() {
        return getNumBiopsia();
    }

    @Override
    public Integer value4() {
        return getNumImagen();
    }

    @Override
    public String value5() {
        return getRutaImagen();
    }

    @Override
    public String value6() {
        return getNombreImagen();
    }

    @Override
    public LocalDate value7() {
        return getFechaCreacion();
    }

    @Override
    public String value8() {
        return getCreadoPor();
    }

    @Override
    public String value9() {
        return getModificadoPor();
    }

    @Override
    public LocalDate value10() {
        return getFechaModificacion();
    }

    @Override
    public LabExamenImagenRecord value1(Integer value) {
        setCodExamen(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value2(String value) {
        setNumFrote(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value3(String value) {
        setNumBiopsia(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value4(Integer value) {
        setNumImagen(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value5(String value) {
        setRutaImagen(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value6(String value) {
        setNombreImagen(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value7(LocalDate value) {
        setFechaCreacion(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value8(String value) {
        setCreadoPor(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value9(String value) {
        setModificadoPor(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord value10(LocalDate value) {
        setFechaModificacion(value);
        return this;
    }

    @Override
    public LabExamenImagenRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, LocalDate value7, String value8, String value9, LocalDate value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabExamenImagenRecord
     */
    public LabExamenImagenRecord() {
        super(LabExamenImagen.LAB_EXAMEN_IMAGEN);
    }

    /**
     * Create a detached, initialised LabExamenImagenRecord
     */
    public LabExamenImagenRecord(Integer codExamen, String numFrote, String numBiopsia, Integer numImagen, String rutaImagen, String nombreImagen, LocalDate fechaCreacion, String creadoPor, String modificadoPor, LocalDate fechaModificacion) {
        super(LabExamenImagen.LAB_EXAMEN_IMAGEN);

        setCodExamen(codExamen);
        setNumFrote(numFrote);
        setNumBiopsia(numBiopsia);
        setNumImagen(numImagen);
        setRutaImagen(rutaImagen);
        setNombreImagen(nombreImagen);
        setFechaCreacion(fechaCreacion);
        setCreadoPor(creadoPor);
        setModificadoPor(modificadoPor);
        setFechaModificacion(fechaModificacion);
    }
}
