/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabReporteFroteVw;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabReporteFroteVwRecord extends TableRecordImpl<LabReporteFroteVwRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_reporte_frote_vw.cod_examen</code>.
     */
    public void setCodExamen(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.cod_examen</code>.
     */
    public Integer getCodExamen() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.num_examen</code>.
     */
    public void setNumExamen(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.num_examen</code>.
     */
    public String getNumExamen() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.fecha_examen</code>.
     */
    public void setFechaExamen(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.fecha_examen</code>.
     */
    public LocalDate getFechaExamen() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.fec_examen</code>.
     */
    public void setFecExamen(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.fec_examen</code>.
     */
    public String getFecExamen() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.nombre_paciente</code>.
     */
    public void setNombrePaciente(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.nombre_paciente</code>.
     */
    public String getNombrePaciente() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.tipo_identificacion</code>.
     */
    public void setTipoIdentificacion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.tipo_identificacion</code>.
     */
    public String getTipoIdentificacion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.identificacion</code>.
     */
    public void setIdentificacion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.identificacion</code>.
     */
    public String getIdentificacion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.ocupacion</code>.
     */
    public void setOcupacion(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.ocupacion</code>.
     */
    public String getOcupacion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.numero_ficha</code>.
     */
    public void setNumeroFicha(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.numero_ficha</code>.
     */
    public String getNumeroFicha() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.enfermedades</code>.
     */
    public void setEnfermedades(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.enfermedades</code>.
     */
    public String getEnfermedades() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.diagnosticos_diferenciales</code>.
     */
    public void setDiagnosticosDiferenciales(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.diagnosticos_diferenciales</code>.
     */
    public String getDiagnosticosDiferenciales() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.estado_examen</code>.
     */
    public void setEstadoExamen(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.estado_examen</code>.
     */
    public String getEstadoExamen() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.doctor_examen</code>.
     */
    public void setDoctorExamen(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.doctor_examen</code>.
     */
    public String getDoctorExamen() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.color_lesion</code>.
     */
    public void setColorLesion(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.color_lesion</code>.
     */
    public String getColorLesion() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.naturaleza_lesion</code>.
     */
    public void setNaturalezaLesion(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.naturaleza_lesion</code>.
     */
    public String getNaturalezaLesion() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.sintoma_lesion</code>.
     */
    public void setSintomaLesion(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.sintoma_lesion</code>.
     */
    public String getSintomaLesion() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.forma_lesion</code>.
     */
    public void setFormaLesion(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.forma_lesion</code>.
     */
    public String getFormaLesion() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.superficie_lesion</code>.
     */
    public void setSuperficieLesion(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.superficie_lesion</code>.
     */
    public String getSuperficieLesion() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.consistencia_lesion</code>.
     */
    public void setConsistenciaLesion(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.consistencia_lesion</code>.
     */
    public String getConsistenciaLesion() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.intraoseo_lesion</code>.
     */
    public void setIntraoseoLesion(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.intraoseo_lesion</code>.
     */
    public String getIntraoseoLesion() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.pieza_lesion</code>.
     */
    public void setPiezaLesion(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.pieza_lesion</code>.
     */
    public String getPiezaLesion() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.tamano_lesion</code>.
     */
    public void setTamanoLesion(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.tamano_lesion</code>.
     */
    public String getTamanoLesion() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.dias_lesion</code>.
     */
    public void setDiasLesion(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.dias_lesion</code>.
     */
    public Integer getDiasLesion() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.meses_lesion</code>.
     */
    public void setMesesLesion(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.meses_lesion</code>.
     */
    public Integer getMesesLesion() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.anios_lesion</code>.
     */
    public void setAniosLesion(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.anios_lesion</code>.
     */
    public Integer getAniosLesion() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.doctor_remision</code>.
     */
    public void setDoctorRemision(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.doctor_remision</code>.
     */
    public String getDoctorRemision() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.dependencia_doctor_remision</code>.
     */
    public void setDependenciaDoctorRemision(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.dependencia_doctor_remision</code>.
     */
    public String getDependenciaDoctorRemision() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.req_frote</code>.
     */
    public void setReqFrote(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.req_frote</code>.
     */
    public String getReqFrote() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.num_frote</code>.
     */
    public void setNumFrote(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.num_frote</code>.
     */
    public String getNumFrote() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.num_muestra_frote</code>.
     */
    public void setNumMuestraFrote(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.num_muestra_frote</code>.
     */
    public String getNumMuestraFrote() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.fec_frote</code>.
     */
    public void setFecFrote(LocalDate value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.fec_frote</code>.
     */
    public LocalDate getFecFrote() {
        return (LocalDate) get(30);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.fecha_frote</code>.
     */
    public void setFechaFrote(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.fecha_frote</code>.
     */
    public String getFechaFrote() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.tincion</code>.
     */
    public void setTincion(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.tincion</code>.
     */
    public String getTincion() {
        return (String) get(32);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.datos_recibo</code>.
     */
    public void setDatosRecibo(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.datos_recibo</code>.
     */
    public String getDatosRecibo() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.valor_recibo</code>.
     */
    public void setValorRecibo(BigDecimal value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.valor_recibo</code>.
     */
    public BigDecimal getValorRecibo() {
        return (BigDecimal) get(34);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.usuario_realiza_frote</code>.
     */
    public void setUsuarioRealizaFrote(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.usuario_realiza_frote</code>.
     */
    public String getUsuarioRealizaFrote() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.estado_frote</code>.
     */
    public void setEstadoFrote(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.estado_frote</code>.
     */
    public String getEstadoFrote() {
        return (String) get(36);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.fecha_informe_frote</code>.
     */
    public void setFechaInformeFrote(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.fecha_informe_frote</code>.
     */
    public String getFechaInformeFrote() {
        return (String) get(37);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.diagnostico_informe_frote</code>.
     */
    public void setDiagnosticoInformeFrote(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.diagnostico_informe_frote</code>.
     */
    public String getDiagnosticoInformeFrote() {
        return (String) get(38);
    }

    /**
     * Setter for <code>public.lab_reporte_frote_vw.usuario_informe_frote</code>.
     */
    public void setUsuarioInformeFrote(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>public.lab_reporte_frote_vw.usuario_informe_frote</code>.
     */
    public String getUsuarioInformeFrote() {
        return (String) get(39);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabReporteFroteVwRecord
     */
    public LabReporteFroteVwRecord() {
        super(LabReporteFroteVw.LAB_REPORTE_FROTE_VW);
    }

    /**
     * Create a detached, initialised LabReporteFroteVwRecord
     */
    public LabReporteFroteVwRecord(Integer codExamen, String numExamen, LocalDate fechaExamen, String fecExamen, String nombrePaciente, String tipoIdentificacion, String identificacion, String ocupacion, String numeroFicha, String enfermedades, String diagnosticosDiferenciales, String estadoExamen, String doctorExamen, String colorLesion, String naturalezaLesion, String sintomaLesion, String formaLesion, String superficieLesion, String consistenciaLesion, String intraoseoLesion, String piezaLesion, String tamanoLesion, Integer diasLesion, Integer mesesLesion, Integer aniosLesion, String doctorRemision, String dependenciaDoctorRemision, String reqFrote, String numFrote, String numMuestraFrote, LocalDate fecFrote, String fechaFrote, String tincion, String datosRecibo, BigDecimal valorRecibo, String usuarioRealizaFrote, String estadoFrote, String fechaInformeFrote, String diagnosticoInformeFrote, String usuarioInformeFrote) {
        super(LabReporteFroteVw.LAB_REPORTE_FROTE_VW);

        setCodExamen(codExamen);
        setNumExamen(numExamen);
        setFechaExamen(fechaExamen);
        setFecExamen(fecExamen);
        setNombrePaciente(nombrePaciente);
        setTipoIdentificacion(tipoIdentificacion);
        setIdentificacion(identificacion);
        setOcupacion(ocupacion);
        setNumeroFicha(numeroFicha);
        setEnfermedades(enfermedades);
        setDiagnosticosDiferenciales(diagnosticosDiferenciales);
        setEstadoExamen(estadoExamen);
        setDoctorExamen(doctorExamen);
        setColorLesion(colorLesion);
        setNaturalezaLesion(naturalezaLesion);
        setSintomaLesion(sintomaLesion);
        setFormaLesion(formaLesion);
        setSuperficieLesion(superficieLesion);
        setConsistenciaLesion(consistenciaLesion);
        setIntraoseoLesion(intraoseoLesion);
        setPiezaLesion(piezaLesion);
        setTamanoLesion(tamanoLesion);
        setDiasLesion(diasLesion);
        setMesesLesion(mesesLesion);
        setAniosLesion(aniosLesion);
        setDoctorRemision(doctorRemision);
        setDependenciaDoctorRemision(dependenciaDoctorRemision);
        setReqFrote(reqFrote);
        setNumFrote(numFrote);
        setNumMuestraFrote(numMuestraFrote);
        setFecFrote(fecFrote);
        setFechaFrote(fechaFrote);
        setTincion(tincion);
        setDatosRecibo(datosRecibo);
        setValorRecibo(valorRecibo);
        setUsuarioRealizaFrote(usuarioRealizaFrote);
        setEstadoFrote(estadoFrote);
        setFechaInformeFrote(fechaInformeFrote);
        setDiagnosticoInformeFrote(diagnosticoInformeFrote);
        setUsuarioInformeFrote(usuarioInformeFrote);
    }
}
