/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabRol;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabRolRecord extends UpdatableRecordImpl<LabRolRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_rol.codigo_rol</code>.
     */
    public void setCodigoRol(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_rol.codigo_rol</code>.
     */
    public Integer getCodigoRol() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_rol.rol_nombre</code>.
     */
    public void setRolNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_rol.rol_nombre</code>.
     */
    public String getRolNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lab_rol.rol_descripcion</code>.
     */
    public void setRolDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_rol.rol_descripcion</code>.
     */
    public String getRolDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lab_rol.rol_estado</code>.
     */
    public void setRolEstado(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_rol.rol_estado</code>.
     */
    public Integer getRolEstado() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LabRol.LAB_ROL.CODIGO_ROL;
    }

    @Override
    public Field<String> field2() {
        return LabRol.LAB_ROL.ROL_NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return LabRol.LAB_ROL.ROL_DESCRIPCION;
    }

    @Override
    public Field<Integer> field4() {
        return LabRol.LAB_ROL.ROL_ESTADO;
    }

    @Override
    public Integer component1() {
        return getCodigoRol();
    }

    @Override
    public String component2() {
        return getRolNombre();
    }

    @Override
    public String component3() {
        return getRolDescripcion();
    }

    @Override
    public Integer component4() {
        return getRolEstado();
    }

    @Override
    public Integer value1() {
        return getCodigoRol();
    }

    @Override
    public String value2() {
        return getRolNombre();
    }

    @Override
    public String value3() {
        return getRolDescripcion();
    }

    @Override
    public Integer value4() {
        return getRolEstado();
    }

    @Override
    public LabRolRecord value1(Integer value) {
        setCodigoRol(value);
        return this;
    }

    @Override
    public LabRolRecord value2(String value) {
        setRolNombre(value);
        return this;
    }

    @Override
    public LabRolRecord value3(String value) {
        setRolDescripcion(value);
        return this;
    }

    @Override
    public LabRolRecord value4(Integer value) {
        setRolEstado(value);
        return this;
    }

    @Override
    public LabRolRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabRolRecord
     */
    public LabRolRecord() {
        super(LabRol.LAB_ROL);
    }

    /**
     * Create a detached, initialised LabRolRecord
     */
    public LabRolRecord(Integer codigoRol, String rolNombre, String rolDescripcion, Integer rolEstado) {
        super(LabRol.LAB_ROL);

        setCodigoRol(codigoRol);
        setRolNombre(rolNombre);
        setRolDescripcion(rolDescripcion);
        setRolEstado(rolEstado);
    }
}
