/*
 * This file is generated by jOOQ.
 */
package histopatologialab.core.db.tables.records;


import histopatologialab.core.db.tables.LabReporteExamenVw;

import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabReporteExamenVwRecord extends TableRecordImpl<LabReporteExamenVwRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lab_reporte_examen_vw.cod_examen</code>.
     */
    public void setCodExamen(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.cod_examen</code>.
     */
    public Integer getCodExamen() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.num_examen</code>.
     */
    public void setNumExamen(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.num_examen</code>.
     */
    public String getNumExamen() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fecha_examen</code>.
     */
    public void setFechaExamen(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fecha_examen</code>.
     */
    public LocalDate getFechaExamen() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fec_examen</code>.
     */
    public void setFecExamen(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fec_examen</code>.
     */
    public String getFecExamen() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.nombre_paciente</code>.
     */
    public void setNombrePaciente(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.nombre_paciente</code>.
     */
    public String getNombrePaciente() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.tipo_identificacion</code>.
     */
    public void setTipoIdentificacion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.tipo_identificacion</code>.
     */
    public String getTipoIdentificacion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.identificacion</code>.
     */
    public void setIdentificacion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.identificacion</code>.
     */
    public String getIdentificacion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.ocupacion</code>.
     */
    public void setOcupacion(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.ocupacion</code>.
     */
    public String getOcupacion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.numero_ficha</code>.
     */
    public void setNumeroFicha(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.numero_ficha</code>.
     */
    public String getNumeroFicha() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.enfermedades</code>.
     */
    public void setEnfermedades(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.enfermedades</code>.
     */
    public String getEnfermedades() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.diagnosticos_diferenciales</code>.
     */
    public void setDiagnosticosDiferenciales(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.diagnosticos_diferenciales</code>.
     */
    public String getDiagnosticosDiferenciales() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.estado_examen</code>.
     */
    public void setEstadoExamen(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.estado_examen</code>.
     */
    public String getEstadoExamen() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.doctor_examen</code>.
     */
    public void setDoctorExamen(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.doctor_examen</code>.
     */
    public String getDoctorExamen() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.color_lesion</code>.
     */
    public void setColorLesion(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.color_lesion</code>.
     */
    public String getColorLesion() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.naturaleza_lesion</code>.
     */
    public void setNaturalezaLesion(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.naturaleza_lesion</code>.
     */
    public String getNaturalezaLesion() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.sintoma_lesion</code>.
     */
    public void setSintomaLesion(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.sintoma_lesion</code>.
     */
    public String getSintomaLesion() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.forma_lesion</code>.
     */
    public void setFormaLesion(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.forma_lesion</code>.
     */
    public String getFormaLesion() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.superficie_lesion</code>.
     */
    public void setSuperficieLesion(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.superficie_lesion</code>.
     */
    public String getSuperficieLesion() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.consistencia_lesion</code>.
     */
    public void setConsistenciaLesion(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.consistencia_lesion</code>.
     */
    public String getConsistenciaLesion() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.intraoseo_lesion</code>.
     */
    public void setIntraoseoLesion(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.intraoseo_lesion</code>.
     */
    public String getIntraoseoLesion() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.pieza_lesion</code>.
     */
    public void setPiezaLesion(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.pieza_lesion</code>.
     */
    public String getPiezaLesion() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.tamano_lesion</code>.
     */
    public void setTamanoLesion(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.tamano_lesion</code>.
     */
    public String getTamanoLesion() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.dias_lesion</code>.
     */
    public void setDiasLesion(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.dias_lesion</code>.
     */
    public Integer getDiasLesion() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.meses_lesion</code>.
     */
    public void setMesesLesion(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.meses_lesion</code>.
     */
    public Integer getMesesLesion() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.anios_lesion</code>.
     */
    public void setAniosLesion(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.anios_lesion</code>.
     */
    public Integer getAniosLesion() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.doctor_remision</code>.
     */
    public void setDoctorRemision(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.doctor_remision</code>.
     */
    public String getDoctorRemision() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.dependencia_doctor_remision</code>.
     */
    public void setDependenciaDoctorRemision(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.dependencia_doctor_remision</code>.
     */
    public String getDependenciaDoctorRemision() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.req_biopsia</code>.
     */
    public void setReqBiopsia(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.req_biopsia</code>.
     */
    public String getReqBiopsia() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.numero_biopsia</code>.
     */
    public void setNumeroBiopsia(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.numero_biopsia</code>.
     */
    public String getNumeroBiopsia() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fec_biopsia</code>.
     */
    public void setFecBiopsia(LocalDate value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fec_biopsia</code>.
     */
    public LocalDate getFecBiopsia() {
        return (LocalDate) get(29);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fecha_biopsia</code>.
     */
    public void setFechaBiopsia(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fecha_biopsia</code>.
     */
    public String getFechaBiopsia() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.muestra_biopsia</code>.
     */
    public void setMuestraBiopsia(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.muestra_biopsia</code>.
     */
    public String getMuestraBiopsia() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.procedimiento_biopsia</code>.
     */
    public void setProcedimientoBiopsia(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.procedimiento_biopsia</code>.
     */
    public String getProcedimientoBiopsia() {
        return (String) get(32);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.tipocirugia_biopsia</code>.
     */
    public void setTipocirugiaBiopsia(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.tipocirugia_biopsia</code>.
     */
    public String getTipocirugiaBiopsia() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.instrumento_biopsia</code>.
     */
    public void setInstrumentoBiopsia(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.instrumento_biopsia</code>.
     */
    public String getInstrumentoBiopsia() {
        return (String) get(34);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.usuario_realiza_biopsia</code>.
     */
    public void setUsuarioRealizaBiopsia(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.usuario_realiza_biopsia</code>.
     */
    public String getUsuarioRealizaBiopsia() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.estado_biopsia</code>.
     */
    public void setEstadoBiopsia(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.estado_biopsia</code>.
     */
    public String getEstadoBiopsia() {
        return (String) get(36);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fecha_informe_biopsia</code>.
     */
    public void setFechaInformeBiopsia(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fecha_informe_biopsia</code>.
     */
    public String getFechaInformeBiopsia() {
        return (String) get(37);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.diagnostico_biopsia</code>.
     */
    public void setDiagnosticoBiopsia(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.diagnostico_biopsia</code>.
     */
    public String getDiagnosticoBiopsia() {
        return (String) get(38);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.usuario_informe_biopsia</code>.
     */
    public void setUsuarioInformeBiopsia(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.usuario_informe_biopsia</code>.
     */
    public String getUsuarioInformeBiopsia() {
        return (String) get(39);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.req_frote</code>.
     */
    public void setReqFrote(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.req_frote</code>.
     */
    public String getReqFrote() {
        return (String) get(40);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.num_frote</code>.
     */
    public void setNumFrote(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.num_frote</code>.
     */
    public String getNumFrote() {
        return (String) get(41);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.num_muestra_frote</code>.
     */
    public void setNumMuestraFrote(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.num_muestra_frote</code>.
     */
    public String getNumMuestraFrote() {
        return (String) get(42);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fec_frote</code>.
     */
    public void setFecFrote(LocalDate value) {
        set(43, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fec_frote</code>.
     */
    public LocalDate getFecFrote() {
        return (LocalDate) get(43);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fecha_frote</code>.
     */
    public void setFechaFrote(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fecha_frote</code>.
     */
    public String getFechaFrote() {
        return (String) get(44);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.tincion</code>.
     */
    public void setTincion(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.tincion</code>.
     */
    public String getTincion() {
        return (String) get(45);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.usuario_realiza_frote</code>.
     */
    public void setUsuarioRealizaFrote(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.usuario_realiza_frote</code>.
     */
    public String getUsuarioRealizaFrote() {
        return (String) get(46);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.estado_frote</code>.
     */
    public void setEstadoFrote(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.estado_frote</code>.
     */
    public String getEstadoFrote() {
        return (String) get(47);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.fecha_informe_frote</code>.
     */
    public void setFechaInformeFrote(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.fecha_informe_frote</code>.
     */
    public String getFechaInformeFrote() {
        return (String) get(48);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.diagnostico_informe_frote</code>.
     */
    public void setDiagnosticoInformeFrote(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.diagnostico_informe_frote</code>.
     */
    public String getDiagnosticoInformeFrote() {
        return (String) get(49);
    }

    /**
     * Setter for <code>public.lab_reporte_examen_vw.usuario_informe_frote</code>.
     */
    public void setUsuarioInformeFrote(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>public.lab_reporte_examen_vw.usuario_informe_frote</code>.
     */
    public String getUsuarioInformeFrote() {
        return (String) get(50);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LabReporteExamenVwRecord
     */
    public LabReporteExamenVwRecord() {
        super(LabReporteExamenVw.LAB_REPORTE_EXAMEN_VW);
    }

    /**
     * Create a detached, initialised LabReporteExamenVwRecord
     */
    public LabReporteExamenVwRecord(Integer codExamen, String numExamen, LocalDate fechaExamen, String fecExamen, String nombrePaciente, String tipoIdentificacion, String identificacion, String ocupacion, String numeroFicha, String enfermedades, String diagnosticosDiferenciales, String estadoExamen, String doctorExamen, String colorLesion, String naturalezaLesion, String sintomaLesion, String formaLesion, String superficieLesion, String consistenciaLesion, String intraoseoLesion, String piezaLesion, String tamanoLesion, Integer diasLesion, Integer mesesLesion, Integer aniosLesion, String doctorRemision, String dependenciaDoctorRemision, String reqBiopsia, String numeroBiopsia, LocalDate fecBiopsia, String fechaBiopsia, String muestraBiopsia, String procedimientoBiopsia, String tipocirugiaBiopsia, String instrumentoBiopsia, String usuarioRealizaBiopsia, String estadoBiopsia, String fechaInformeBiopsia, String diagnosticoBiopsia, String usuarioInformeBiopsia, String reqFrote, String numFrote, String numMuestraFrote, LocalDate fecFrote, String fechaFrote, String tincion, String usuarioRealizaFrote, String estadoFrote, String fechaInformeFrote, String diagnosticoInformeFrote, String usuarioInformeFrote) {
        super(LabReporteExamenVw.LAB_REPORTE_EXAMEN_VW);

        setCodExamen(codExamen);
        setNumExamen(numExamen);
        setFechaExamen(fechaExamen);
        setFecExamen(fecExamen);
        setNombrePaciente(nombrePaciente);
        setTipoIdentificacion(tipoIdentificacion);
        setIdentificacion(identificacion);
        setOcupacion(ocupacion);
        setNumeroFicha(numeroFicha);
        setEnfermedades(enfermedades);
        setDiagnosticosDiferenciales(diagnosticosDiferenciales);
        setEstadoExamen(estadoExamen);
        setDoctorExamen(doctorExamen);
        setColorLesion(colorLesion);
        setNaturalezaLesion(naturalezaLesion);
        setSintomaLesion(sintomaLesion);
        setFormaLesion(formaLesion);
        setSuperficieLesion(superficieLesion);
        setConsistenciaLesion(consistenciaLesion);
        setIntraoseoLesion(intraoseoLesion);
        setPiezaLesion(piezaLesion);
        setTamanoLesion(tamanoLesion);
        setDiasLesion(diasLesion);
        setMesesLesion(mesesLesion);
        setAniosLesion(aniosLesion);
        setDoctorRemision(doctorRemision);
        setDependenciaDoctorRemision(dependenciaDoctorRemision);
        setReqBiopsia(reqBiopsia);
        setNumeroBiopsia(numeroBiopsia);
        setFecBiopsia(fecBiopsia);
        setFechaBiopsia(fechaBiopsia);
        setMuestraBiopsia(muestraBiopsia);
        setProcedimientoBiopsia(procedimientoBiopsia);
        setTipocirugiaBiopsia(tipocirugiaBiopsia);
        setInstrumentoBiopsia(instrumentoBiopsia);
        setUsuarioRealizaBiopsia(usuarioRealizaBiopsia);
        setEstadoBiopsia(estadoBiopsia);
        setFechaInformeBiopsia(fechaInformeBiopsia);
        setDiagnosticoBiopsia(diagnosticoBiopsia);
        setUsuarioInformeBiopsia(usuarioInformeBiopsia);
        setReqFrote(reqFrote);
        setNumFrote(numFrote);
        setNumMuestraFrote(numMuestraFrote);
        setFecFrote(fecFrote);
        setFechaFrote(fechaFrote);
        setTincion(tincion);
        setUsuarioRealizaFrote(usuarioRealizaFrote);
        setEstadoFrote(estadoFrote);
        setFechaInformeFrote(fechaInformeFrote);
        setDiagnosticoInformeFrote(diagnosticoInformeFrote);
        setUsuarioInformeFrote(usuarioInformeFrote);
    }
}
